#!/bin/bash

die () {
    echo
    echo "$*"
    echo
    exit 1
}

file="args.apk.gn"
srcdir="$(dirname $0)/../../chromium-src/args"

if [ -d "$srcdir" ]; then
	if [ -e "$srcdir/$file" ]; then
		[ -d "$(dirname $0)/config" ] || mkdir -v "$(dirname $0)/config"
		cp -Lv "$srcdir/$file" "$(dirname $0)/config"/args.gn
		sed -e '/^chrome_public_manifest_package/d' -e '/^target_cpu/s/64//' \
			-i "$(dirname $0)/config"/args.gn
		echo 'chrome_public_manifest_package = "org.chromium.stable"' >>"$(dirname $0)/config"/args.gn
	else
		die No such file: $srcdir/$file
	fi
else
	die No such directory: $srcdir
fi
