#!/bin/bash

die () {
    echo
    echo "$*"
    echo
    exit 1
}

file="args.apk.gn"
srcdir="$(dirname $0)/../../chromium-src/args"

if [ -d "$srcdir" ]; then
	if [ -e "$srcdir/$file" ]; then
		[ -d "$(dirname $0)/config" ] || mkdir -v "$(dirname $0)/config"
		cp -Lv "$srcdir/$file" "$(dirname $0)/config"/args.gn
		sed -e '/^google_api_key/d' -e '/^google_default_client_id/d' -e '/^google_default_client_secret/d' \
			-e '/^chrome_public_manifest_package/d' -i "$(dirname $0)/config"/args.gn
		echo 'webview_devui_show_icon = true' >>"$(dirname $0)/config"/args.gn
	else
		die No such file: $srcdir/$file
	fi
else
	die No such directory: $srcdir
fi
