#!/bin/bash

die () {
    echo
    echo "$*"
    echo
    exit 1
}

file="args.linux.gn"
srcdir="$(dirname $0)/../../chromium-src/args"

if [ -d "$srcdir" ]; then
	if [ -e "$srcdir/$file" ]; then
		[ -d "$(dirname $0)/config" ] || mkdir -v "$(dirname $0)/config"
		cp -Lv "$srcdir/$file" "$(dirname $0)/config"/args.gn
	else
		die No such file: $srcdir/$file
	fi
else
	die No such directory: $srcdir
fi
