#!/bin/bash


ver="$(<VERSION)"
git config --global user.name 'github-actions'
git config --global user.email 'noreply@github.com'

_exit() {
	local d="$(realpath $2)"
	echo "Directory '$d' does not exist!"
	exit $1
}

_docmd() {
	[ -d src ] || mkdir src

	pushd src-$ver >/dev/null 2>&1
	cat $ver.src.part.tar.xz.[0-9]* > $ver.src.tar.xz
	sha512sum -c sha512
	printf "  -> Extracting the $ver.src.tar.xz..."
	tar xf $ver.src.tar.xz -C ../src; printf ' done.\n'
	popd >/dev/null 2>&1
	rm -f src-$ver/*
}

_docmd
