#!/bin/bash


gn_url="https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-amd64/+/latest"
#https://chrome-infra-packages.appspot.com/p/gn/gn/linux-amd64/+/
commit="050417b30319b9a97a78d6aa29c2fc3e7805d65a"


_docmd() {
	printf 'Download gn from CIPD Packages..'
	wget -c -q "${gn_url}" -O gn.zip
	[ -d bin ] || mkdir bin
	unzip gn.zip gn -d bin >/dev/null
	rm gn.zip
	printf 'done.\n'

	printf 'Download the latest version of Ninja from GitHub...'
	wget -c -q https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip
	unzip ninja-linux.zip ninja -d bin >/dev/null
	rm ninja-linux.zip
	printf 'done.\n'

	printf "Get bash script: 'install-build-deps'..."
	curl -s "https://chromium.googlesource.com/chromium/src/+/${commit}/build/install-build-deps.sh?format=TEXT" | base64 -d >bin/install-build-deps
	printf 'done.\n'

	chmod 755 bin/{gn,ninja,install-build-deps}
}

_docmd
