#!/bin/bash

ver="$(<VERSION)"
export TZ='Asia/Shanghai'

_docmd() {
	pushd build-$ver >/dev/null 2>&1
	cat $ver.bld.part.tar.xz.[0-9]* > $ver.bld.tar.xz
	sha512sum -c sha512
	printf "  -> Extracting the $ver.bld.tar.xz..."
	tar xf $ver.bld.tar.xz -C ..
	printf ' done.\n'
	popd >/dev/null 2>&1
	rm -rf build-$ver
	git commit --all --message "removed old build-cache in $(date|sed -e 's/20[0-9][0-9]$//' -e 's/CST//')"
}

_docmd
