#!/bin/bash

ver="$(<VERSION)"
export PATH="$PWD/bin":"$PWD/depot_tools":$PATH DEPOT_TOOLS_UPDATE=0
export VPYTHON_BYPASS='manually managed python not supported by chrome operations'

if [ -f 'EPOCH' ]; then
	epoch="$(<EPOCH)"
else
	epoch="$(date +%s)"
	echo "${epoch}" >EPOCH
	git add EPOCH
fi

_rsync_src() {
	[ -e '.gclient' ] || mv config/gclient .gclient
	echo 'Run gclient sync...'
	gclient sync --no-history --nohooks
	src/build/util/lastchange.py -o src/build/util/LASTCHANGE
	src/build/util/lastchange.py -m GPU_LISTS_VERSION --revision-id-only --header src/gpu/config/gpu_lists_version.h
	src/build/util/lastchange.py -m SKIA_COMMIT_HASH -s src/third_party/skia --header src/skia/ext/skia_commit_hash.h
	src/build/util/lastchange.py -s src/third_party/dawn --revision src/gpu/webgpu/DAWN_VERSION
	src/tools/update_pgo_profiles.py --target=linux update --gs-url-base=chromium-optimization-profiles/pgo_profiles
	download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs -s src/third_party/node/node_modules.tar.gz.sha1
	find src/third_party/jdk/current -type f -delete
}

_rsync_tools() {
	pushd src >/dev/null 2>&1
	python3 tools/clang/scripts/update.py
	python3 build/linux/sysroot_scripts/install-sysroot.py --arch=amd64
	popd >/dev/null 2>&1
}

_docmd() {
	_rsync_src
	_rsync_tools
	find src -exec touch -cd @${epoch} {} +
	[ ! -d out ] || mv -v out src/
}

_docmd
