#!/bin/bash

if test -n "$(grep '^target_cpu' config/args.gn|grep 'x64')"; then
	bit=64
elif test -n "$(grep '^target_cpu' config/args.gn|grep 'x86')"; then
	bit=32
fi
build_dir="src/out/win$bit"

_docmd() {
	if [ -f "${build_dir}/build.ninja" ]
	then
		echo "The file '${build_dir}/build.ninja' already exists, skipping!"
	else
		[ -d "${build_dir}" ] || mkdir -pv "${build_dir}"
		export PATH="$PWD/bin":$PATH
		cp config/args.gn ${build_dir}/args.gn
	    pushd src >/dev/null 2>&1
		echo '  -> Gen args.gn ...'
		gn gen "${build_dir#src/}" --filters=//chrome
	    popd >/dev/null 2>&1
	fi
}

_docmd
