#!/bin/bash


ver="$(<VERSION)"
build_dir="src/out/android"
export NINJA_STATUS="[%r %f/%t] "
export PATH="$PWD/bin":$PATH

_docmd() {
	timeout 18000 ninja -C $build_dir chrome_public_apk || true
}

_docmd
